name: Deployment Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Deploy to production
        id: deploy
        env:
          COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ' ') }}
        if: ${{ github.event_name == 'push' && !contains(env.COMMIT_MESSAGES, '#skip') }}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
      - name: Test Failure
        uses: BubbleProd/discord-webhook-notify@v2
        if: failure()
        with:
            severity: error
            details: Pipeline failed
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failure at Deploy
        uses: BubbleProd/discord-webhook-notify@v2
        if: ${{ steps.deploy.conclusion == 'failure' }}
        with:
            severity: error
            details: ${{ steps.deploy.outputs.message }}
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    needs: simple_deployment_pipeline
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
      - name: Test success
        uses: BubbleProd/discord-webhook-notify@v2
        if: success()
        with:
            severity: success
            details: Pipeline success
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      
